// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rymkzffhyudonfrpazlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5bWt6ZmZoeXVkb25mcnBhemxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDE2MTEsImV4cCI6MjA2OTExNzYxMX0.o5HOFLvvi4qrdmcTsOZK7uxvDUvYebvKl7G4jRxeX_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});